const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const vm=require('node:vm');
test('native queue survives module restart, retains copied media after offline failure, and removes it only after receipt',async()=>{
 const dir=await fs.mkdtemp(path.join(os.tmpdir(),'inicio-queue-'));const storage={async getItem(key){try{return await fs.readFile(path.join(dir,encodeURIComponent(key)),'utf8');}catch(e){if(e.code==='ENOENT')return null;throw e;}},async setItem(key,value){await fs.writeFile(path.join(dir,encodeURIComponent(key)),value);}};
 const files={documentDirectory:dir+'/',async makeDirectoryAsync(p){await fs.mkdir(p,{recursive:true});},async copyAsync({from,to}){await fs.copyFile(from,to);},async deleteAsync(p){await fs.rm(p,{recursive:true,force:true});},async getInfoAsync(p){try{await fs.stat(p);return{exists:true};}catch{return{exists:false};}}};
 let connected=false,calls=0;const accepted=[];const api={async submitDiary(id,form){calls++;if(!connected)throw new Error('Offline');accepted.push([id,form]);return{recordId:42,status:'submitted'};}};
 const source=await fs.readFile(path.join(__dirname,'../expo-mobile/src/diaryQueue.ts'),'utf8');const ts=require('../expo-mobile/node_modules/typescript');const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText;
 function load(){class MockFile extends Blob{constructor(uri){super([require('node:fs').readFileSync(uri)]);this.name=path.basename(uri);}}const module={exports:{}};const sandbox={module,exports:module.exports,FormData,console,require(name){if(name.includes('async-storage'))return storage;if(name==='expo-file-system/legacy')return files;if(name==='expo-file-system')return{File:MockFile};if(name==='./api')return{api};throw new Error(name);}};vm.runInNewContext(compiled,sandbox);return module.exports;}
 try{
  const camera=path.join(dir,'camera.jpg');await fs.writeFile(camera,'Original photograph');let queue=load();const packet={id:'persist_packet_123456',respondentId:7,kind:'standard',fields:{answers_json:'{"1":"A"}',occurrence_time:'2026-09-06T10:00:00Z'},media:[{uri:camera,fileName:'evidence.jpg',mimeType:'image/jpeg',field:'photo_q_2'}],state:'pending',attempts:0,createdAt:'2026-09-06'};
  await queue.enqueue(packet);const saved=(await queue.listQueue(7))[0];assert.notEqual(saved.media[0].uri,camera);await fs.rm(camera);await queue.syncQueue(7);assert.equal(calls,1);assert.equal((await queue.listQueue(7))[0].state,'pending');assert.equal(await fs.readFile(saved.media[0].uri,'utf8'),'Original photograph');
  queue=load();assert.equal((await queue.listQueue(7)).length,1);assert.equal((await queue.listQueue(8)).length,0);connected=true;await queue.syncQueue(7);assert.equal(accepted.length,1);assert.equal(accepted[0][1].get('submission_id'),packet.id);assert.equal((await queue.listQueue(7)).length,0);await assert.rejects(fs.stat(saved.media[0].uri),{code:'ENOENT'});
 }finally{await fs.rm(dir,{recursive:true,force:true});}
});
